# Generated by Django 5.0.1 on 2024-01-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testint',
            name='my_integer',
            field=models.IntegerField(default=0),
        ),
    ]
