# Generated by Django 5.0.1 on 2024-01-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0002_testint_my_integer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStrings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_string', models.TextField()),
            ],
        ),
    ]
